# Generated by Django 3.1.2 on 2020-10-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Profile',
        ),
    ]
