# Generated by Django 3.1.2 on 2020-12-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0004_auto_20201030_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='username',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='result',
            field=models.CharField(max_length=10000),
        ),
    ]
