# Generated by Django 3.1.2 on 2020-12-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0005_auto_20201206_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='username',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
