# Generated by Django 3.1.2 on 2020-12-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0008_auto_20201206_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='result',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
