# Generated by Django 3.1.2 on 2020-12-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0009_auto_20201206_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='result_clean',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
