# Generated by Django 3.1.2 on 2020-12-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0010_auto_20201206_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
