# Generated by Django 3.1.2 on 2020-12-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0011_human_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='result',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='result_clean',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
