# Generated by Django 3.1.2 on 2020-12-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0013_auto_20201206_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
