# Generated by Django 3.1.2 on 2020-12-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0014_auto_20201206_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
