# Generated by Django 3.1.2 on 2020-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0015_auto_20201206_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='response_status',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
