# Generated by Django 3.1.2 on 2020-12-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0017_human_result_clean_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
