# Generated by Django 3.1.2 on 2020-12-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0018_human_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='id',
        ),
        migrations.AlterField(
            model_name='human',
            name='search_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jurorsearch.query'),
        ),
    ]
