# Generated by Django 3.1.2 on 2021-01-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurorsearch', '0021_userdetail_toggle_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='toggle_favorites',
            new_name='toggle_view_favorites',
        ),
    ]
